import { createFileRoute, Link, notFound } from "@tanstack/react-router";
import { RadarScore } from "@/components/charts/RadarScore";
import { ScoreBar } from "@/components/charts/ScoreBar";
import { Button } from "@/components/ui/button";
import { ArrowLeft, Download, FileText, TrendingUp, AlertTriangle, Target } from "lucide-react";
import { Logo } from "@/components/site/Logo";
import { getReport } from "@/lib/assessments.functions";
import { getAssessment, SAMPLE_FACT_SCORES, SAMPLE_LEADERSHIP_SCORES } from "@/data/assessments";
import { getPersonalityProfile } from "@/data/personality-profiles";

const SAMPLE_IDS = new Set(["fact-360", "leadership-360"]);

function buildSample(id: string) {
  const assessment = getAssessment(id);
  if (!assessment) return null;
  const isLeadership = id === "leadership-360";
  const scores = isLeadership ? SAMPLE_LEADERSHIP_SCORES : SAMPLE_FACT_SCORES;
  const section_scores = assessment.sections.reduce((acc: Record<string, any>, s: any, i: number) => {
    const vals = Object.values(scores).slice(0, -1) as number[];
    const raw = vals[i % vals.length] ?? 60;
    acc[s.id] = { name: s.name, score: isLeadership ? Math.round(raw * 20) : raw, weight: s.weight };
    return acc;
  }, {} as Record<string, { name: string; score: number; weight: number }>);
  const overall_score = isLeadership
    ? Math.round((SAMPLE_LEADERSHIP_SCORES.overall as number) * 20)
    : SAMPLE_FACT_SCORES.overall;
  return {
    attempt_id: id,
    assessment: { name: assessment.name, tagline: assessment.tagline },
    attempt: { submitted_at: new Date().toISOString() },
    section_scores,
    overall_score,
    executive_summary: `This is a sample ${assessment.name} report. It illustrates how FACT 360° translates raw scores into an executive narrative — pinpointing where your organization is strong, where it lags, and what to do next. In a live engagement, this section is generated by AI using your real answers and business context.`,
    growth_opportunity: "Prioritize the two lowest-scoring pillars this quarter. Small structural fixes here compound the fastest.",
    strengths: [
      "Strong brand equity in core geography",
      "Committed founder-led leadership",
      "Cash discipline through cycles",
      "Loyal customer base with high repeat rate",
      "Emerging second-line talent",
    ],
    gaps: [
      "Limited digital MIS visibility",
      "Founder-dependent decision making",
      "Undocumented SOPs across shifts",
      "Weak collections follow-through",
      "No structured L&D calendar",
      "Marketing spend not measured",
    ],
    action_plan: [
      { priority: "P1", title: "Deploy MIS Dashboard", outcome: "Real-time visibility on 6 pillars", timeframe: "30 days" },
      { priority: "P1", title: "Document Top-5 SOPs", outcome: "Reduce founder dependence", timeframe: "45 days" },
      { priority: "P2", title: "Weekly Collections Review", outcome: "DSO down 10 days", timeframe: "60 days" },
      { priority: "P2", title: "Second-line Leadership Plan", outcome: "Bench strength across depts", timeframe: "90 days" },
      { priority: "P3", title: "Marketing Attribution Setup", outcome: "Measure spend ROI", timeframe: "60 days" },
      { priority: "P3", title: "Quarterly Business Review", outcome: "Cadence of accountability", timeframe: "Ongoing" },
    ],
  };
}

export const Route = createFileRoute("/report/landscape/$id")({
  ssr: false,
  loader: async ({ params }) => {
    if (SAMPLE_IDS.has(params.id)) {
      const s = buildSample(params.id);
      if (s) return s;
    }
    try {
      return await getReport({ data: { attemptId: params.id } });
    } catch {
      throw notFound();
    }
  },
  notFoundComponent: () => <div className="p-8">Report not found.</div>,
  component: Landscape,
});

function Landscape() {
  const report = Route.useLoaderData() as any;
  const a = report.assessment;
  const submittedAt = report.attempt?.submitted_at
    ? new Date(report.attempt.submitted_at).toLocaleDateString("en-IN", { month: "long", year: "numeric" })
    : "—";
  const sectionScores: Record<string, { name: string; score: number; weight: number }> = report.section_scores ?? {};
  const radar = Object.values(sectionScores).map((s) => ({ area: s.name, value: s.score }));
  const strengths: string[] = report.strengths ?? [];
  const gaps: string[] = report.gaps ?? [];
  const actionPlan: { priority: string; title: string; outcome: string; timeframe: string }[] = report.action_plan ?? [];
  const overall = report.overall_score ?? 0;
  const level = overall >= 80 ? "LEVEL 4 — Optimised"
    : overall >= 60 ? "LEVEL 3 — Systemised"
    : overall >= 40 ? "LEVEL 2 — Market Accepted"
    : "LEVEL 1 — Foundational";

  const profile = getPersonalityProfile((report as any).type_code);
  const dim = (report as any).dimension_scores as any;
  const dimRows = dim
    ? [
        { title: "Energy & Interaction", left: "E", right: "I", leftPct: dim.EI?.ePct, leader: dim.EI?.leader },
        { title: "Information & Learning", left: "S", right: "N", leftPct: dim.SN?.sPct, leader: dim.SN?.leader },
        { title: "Decision Making", left: "T", right: "F", leftPct: dim.TF?.tPct, leader: dim.TF?.leader },
        { title: "Lifestyle & Planning", left: "J", right: "P", leftPct: dim.JP?.jPct, leader: dim.JP?.leader },
      ].filter((d) => typeof d.leftPct === "number")
    : [];

  const Header = () => (
    <div className="bg-primary text-primary-foreground px-4 md:px-6 py-4 flex flex-col md:flex-row md:items-center md:justify-between gap-3 rounded-t-lg">
      <div className="flex items-center gap-3 md:gap-4 min-w-0">
        <Logo inverse />
        <div className="hidden md:block h-10 w-px bg-white/30" />
        <div className="min-w-0">
          <h1 className="text-lg md:text-2xl font-extrabold leading-tight uppercase truncate">{a?.name}</h1>
          <p className="text-accent font-semibold text-xs md:text-sm">{a?.tagline ?? "Business Health at a Glance"}</p>
        </div>
      </div>
      <div className="text-xs md:text-right bg-white/5 px-3 py-2 rounded self-start md:self-auto">
        <div>Assessment Date: <span className="text-accent font-semibold">{submittedAt}</span></div>
        <div>Maturity Level: <span className="text-accent font-semibold">{level}</span></div>
      </div>
    </div>
  );

  return (
    <>
      <style>{`
        @media print {
          /* margin:0 removes the browser's date/title/URL header & footer */
          @page { size: A4 landscape; margin: 0; }
          html, body, * { -webkit-print-color-adjust: exact !important; print-color-adjust: exact !important; }
          body { background: #fff !important; }
          .no-print { display: none !important; }
          .print-page {
            break-after: page; page-break-after: always;
            padding: 12mm 14mm 14mm 14mm;
            box-sizing: border-box;
          }
          .print-page:last-of-type { break-after: auto; page-break-after: auto; }
          .print-page > * { break-inside: avoid; page-break-inside: avoid; }
        }
      `}</style>

      <div className="no-print bg-muted/40 border-b">
        <div className="container-page py-3 flex items-center justify-between gap-2 flex-wrap">
          {SAMPLE_IDS.has(report.attempt_id) ? (
            <Link to="/sample-reports" className="text-sm text-primary inline-flex items-center gap-1">
              <ArrowLeft className="h-4 w-4" /> Back to Sample Reports
            </Link>
          ) : (
            <Link to={"/dashboard/report/$id" as any} params={{ id: report.attempt_id } as any} className="text-sm text-primary inline-flex items-center gap-1">
              <ArrowLeft className="h-4 w-4" /> Back to Report
            </Link>
          )}
          <Button onClick={() => window.print()} className="bg-primary hover:bg-primary/90" size="sm">
            <Download className="h-4 w-4 mr-1" /> Print / Save PDF
          </Button>
        </div>
      </div>

      <div className="mx-auto bg-background p-4 md:p-6 max-w-[1400px] print:p-0 print:max-w-none space-y-6">

        {/* Page 1 — Assessment header + 360° scorecard + overall score */}
        <section className="print-page border border-border rounded-lg overflow-hidden bg-white print:border-0">
          <Header />
          <div className="p-4 md:p-6">
            <div className="bg-primary text-primary-foreground px-3 py-1.5 text-xs font-bold uppercase tracking-wider rounded">360° Scorecard</div>
            <div className="mt-4 grid md:grid-cols-2 gap-x-8 gap-y-3">
              {radar.map((r) => <ScoreBar key={r.area} label={r.area} value={r.value} />)}
            </div>
            <div className="mt-6 rounded bg-primary text-primary-foreground p-4 flex items-center justify-between">
              <div className="text-sm font-bold uppercase">Overall Score</div>
              <div className="text-3xl font-extrabold text-accent">{overall}%</div>
            </div>
          </div>
        </section>

        {/* Page 2 — How this report was built + radar */}
        <section className="print-page border border-border rounded-lg overflow-hidden bg-white print:border-0">
          <div className="p-4 md:p-6 grid md:grid-cols-2 gap-6">
            <div className="space-y-3">
              <div className="bg-accent text-accent-foreground px-3 py-1.5 text-xs font-bold uppercase tracking-wider rounded">
                How this report was built
              </div>
              <p className="text-sm text-muted-foreground leading-relaxed">
                Every answer carries a weight (1–5). Each section's weighted average becomes its score, and within
                each pair of opposite styles the higher-weighted side is declared the dominant pole. Those dominant
                poles decide which guidance, strengths, gaps and actions appear throughout this report.
              </p>
              {dimRows.length > 0 && (
                <div className="space-y-2 pt-1">
                  {dimRows.map((d) => (
                    <div key={d.title}>
                      <div className="flex justify-between text-[11px] font-semibold text-primary">
                        <span>{d.title}</span>
                        <span>{d.leader === "balanced" ? "Balanced" : `${d.leftPct}% / ${100 - (d.leftPct as number)}%`}</span>
                      </div>
                      <div className="mt-1 flex h-2 overflow-hidden rounded-full bg-secondary">
                        <div className="h-full bg-primary" style={{ width: `${d.leftPct}%` }} />
                        <div className="h-full bg-accent" style={{ width: `${100 - (d.leftPct as number)}%` }} />
                      </div>
                    </div>
                  ))}
                </div>
              )}
            </div>
            <div>
              <div className="bg-primary text-primary-foreground px-3 py-1.5 text-xs font-bold uppercase tracking-wider rounded">360° Radar View</div>
              <div className="mt-2"><RadarScore data={radar} height={330} color="var(--color-destructive)" /></div>
            </div>
          </div>
        </section>

        {/* Page 3 — Strengths & key gaps */}
        <section className="print-page border border-border rounded-lg overflow-hidden bg-white print:border-0">
          <div className="p-4 md:p-6 grid md:grid-cols-2 gap-6">
            <div>
              <div className="bg-success text-success-foreground px-3 py-1.5 text-xs font-bold uppercase tracking-wider rounded flex items-center gap-1"><TrendingUp className="h-3 w-3" /> Top Strengths</div>
              <ul className="mt-3 space-y-2 text-sm text-muted-foreground">
                {strengths.slice(0, 5).map((s, i) => <li key={i}><b className="text-primary">{i + 1}.</b> {s}</li>)}
                {strengths.length === 0 && <li>No strengths analyzed.</li>}
              </ul>
              {profile && (
                <ul className="mt-4 space-y-1.5 text-sm text-muted-foreground">
                  {profile.strengths.slice(0, 4).map((s: string) => <li key={s}>✔ {s}</li>)}
                </ul>
              )}
            </div>
            <div>
              <div className="bg-destructive text-destructive-foreground px-3 py-1.5 text-xs font-bold uppercase tracking-wider rounded flex items-center gap-1"><AlertTriangle className="h-3 w-3" /> Key Gaps</div>
              <ul className="mt-3 space-y-2 text-sm text-muted-foreground">
                {gaps.slice(0, 6).map((g, i) => <li key={i}>• {g}</li>)}
                {gaps.length === 0 && <li>No gaps identified.</li>}
              </ul>
              {profile && (
                <ul className="mt-4 space-y-1.5 text-sm text-muted-foreground">
                  {profile.weaknesses.slice(0, 4).map((s: string) => <li key={s}>! {s}</li>)}
                </ul>
              )}
            </div>
          </div>
        </section>

        {/* Page 4 — Executive summary, growth opportunity & development focus */}
        <section className="print-page border border-border rounded-lg overflow-hidden bg-white print:border-0">
          <div className="p-4 md:p-6 pt-8 print:pt-10">
            <div className="grid md:grid-cols-3 gap-6">
              <div className="md:col-span-2">
                <div className="bg-primary text-primary-foreground px-3 py-1.5 text-xs font-bold uppercase tracking-wider rounded">Executive Summary</div>
                <p className="mt-3 text-sm italic text-primary leading-relaxed whitespace-pre-line">{report.executive_summary}</p>
                {profile && (
                  <div className="mt-5 grid sm:grid-cols-3 gap-3 text-sm">
                    <div><div className="font-bold text-primary text-xs uppercase">Communication</div><p className="text-muted-foreground">{profile.communication}</p></div>
                    <div><div className="font-bold text-primary text-xs uppercase">Workplace Style</div><p className="text-muted-foreground">{profile.workplace}</p></div>
                    <div><div className="font-bold text-primary text-xs uppercase">Leadership</div><p className="text-muted-foreground">{profile.leadership}</p></div>
                  </div>
                )}
              </div>
              <div>
                <div className="bg-accent text-accent-foreground px-3 py-1.5 text-xs font-bold uppercase tracking-wider rounded flex items-center gap-1"><Target className="h-3 w-3" /> Growth Opportunity</div>
                <p className="mt-3 text-sm text-primary leading-relaxed">{report.growth_opportunity ?? "—"}</p>
                {profile && (
                  <div className="mt-4 rounded bg-primary text-primary-foreground p-3 text-sm">
                    <p><span className="font-semibold text-accent">Best contribution:</span> {profile.bestContribution}</p>
                    <p className="mt-2"><span className="font-semibold text-accent">Watch area:</span> {profile.watchArea}</p>
                  </div>
                )}
              </div>
            </div>

            {profile && profile.development?.length > 0 && (
              <div className="mt-8">
                <div className="bg-accent text-accent-foreground px-3 py-1.5 text-xs font-bold uppercase tracking-wider rounded">Development Focus</div>
                <ul className="mt-3 grid md:grid-cols-2 gap-2 text-sm text-muted-foreground">
                  {profile.development.map((d: string) => <li key={d}>→ {d}</li>)}
                </ul>
              </div>
            )}
          </div>
        </section>

        {/* Page 5 — Priority action plan */}
        <section className="print-page border border-border rounded-lg overflow-hidden bg-white print:border-0">
          <div className="p-4 md:p-6 pt-8 print:pt-10">
            <div className="bg-primary text-primary-foreground px-3 py-1.5 text-xs font-bold uppercase tracking-wider rounded">Priority Action Plan</div>
            <div className="grid md:grid-cols-3 gap-3 mt-3 text-xs">
              {actionPlan.map((ap, i) => (
                <div key={i} className="border border-border rounded p-3">
                  <div className="flex items-center justify-between">
                    <b className="text-primary">{ap.title}</b>
                    <span className="text-accent font-bold">{ap.priority}</span>
                  </div>
                  <div className="text-muted-foreground mt-1">{ap.outcome}</div>
                  <div className="text-muted-foreground mt-1 italic">⏱ {ap.timeframe}</div>
                </div>
              ))}
            </div>


            <div className="mt-8 bg-primary text-primary-foreground px-4 py-3 rounded flex flex-col md:flex-row md:items-center md:justify-between gap-2 text-xs">
              <div className="flex flex-wrap items-center gap-x-2 gap-y-1 font-bold tracking-wider">
                <span>ASSESS</span><span className="text-accent">→</span><span>DIAGNOSE</span><span className="text-accent">→</span>
                <span>RECOMMEND</span><span className="text-accent">→</span><span>TRANSFORM</span><span className="text-accent">→</span><span>GROW</span>
              </div>
              <div className="flex items-center gap-1 text-accent"><FileText className="h-3.5 w-3.5" /> AI-generated by FACT 360°</div>
            </div>
          </div>
        </section>
      </div>
    </>
  );
}

