alter table public.questions add column if not exists code text;
alter table public.profiles add column if not exists email text;

with bank(section_order, q_order, q_text, dim, q_code) as (
values
  (1,1,'I enjoy meeting new people.','E','E1'),
  (1,2,'I like talking with different people.','E','E2'),
  (1,3,'I feel energetic after social events.','E','E3'),
  (1,4,'I usually start conversations.','E','E4'),
  (1,5,'I enjoy working in teams.','E','E5'),
  (1,6,'I speak my ideas openly.','E','E6'),
  (1,7,'I enjoy busy environments.','E','E7'),
  (1,8,'I make friends easily.','E','E8'),
  (1,9,'I enjoy networking.','E','E9'),
  (1,10,'I like group activities.','E','E10'),
  (1,11,'I enjoy spending time alone.','I','I1'),
  (1,12,'I think before I speak.','I','I2'),
  (1,13,'I like quiet places.','I','I3'),
  (1,14,'I keep many thoughts to myself.','I','I4'),
  (1,15,'Too much social activity tires me.','I','I5'),
  (1,16,'I prefer a few close friends.','I','I6'),
  (1,17,'I enjoy working alone.','I','I7'),
  (1,18,'I need quiet time to recharge.','I','I8'),
  (1,19,'I observe more than I talk.','I','I9'),
  (1,20,'I enjoy reading or reflecting alone.','I','I10'),
  (2,1,'I notice small details.','S','S1'),
  (2,2,'I trust facts.','S','S2'),
  (2,3,'I learn best through experience.','S','S3'),
  (2,4,'I like clear instructions.','S','S4'),
  (2,5,'I prefer practical ideas.','S','S5'),
  (2,6,'I rely on proven methods.','S','S6'),
  (2,7,'I notice changes quickly.','S','S7'),
  (2,8,'I enjoy solving real problems.','S','S8'),
  (2,9,'I remember facts easily.','S','S9'),
  (2,10,'I focus on what is happening now.','S','S10'),
  (2,11,'I enjoy imagining possibilities.','N','N1'),
  (2,12,'I think about the future.','N','N2'),
  (2,13,'I enjoy creative ideas.','N','N3'),
  (2,14,'I like trying new methods.','N','N4'),
  (2,15,'I enjoy learning theories.','N','N5'),
  (2,16,'I see the big picture.','N','N6'),
  (2,17,'I enjoy brainstorming.','N','N7'),
  (2,18,'I often ask ''What if?''','N','N8'),
  (2,19,'I connect ideas easily.','N','N9'),
  (2,20,'I enjoy innovation.','N','N10'),
  (3,1,'I make decisions using facts.','T','T1'),
  (3,2,'I stay calm under pressure.','T','T2'),
  (3,3,'I solve problems logically.','T','T3'),
  (3,4,'I value fairness.','T','T4'),
  (3,5,'I give honest feedback.','T','T5'),
  (3,6,'I enjoy analyzing situations.','T','T6'),
  (3,7,'I like objective discussions.','T','T7'),
  (3,8,'I separate emotions from decisions.','T','T8'),
  (3,9,'I challenge weak ideas.','T','T9'),
  (3,10,'I focus on results.','T','T10'),
  (3,11,'I think about people''s feelings.','F','F1'),
  (3,12,'I value harmony.','F','F2'),
  (3,13,'I enjoy helping others.','F','F3'),
  (3,14,'I avoid hurting others.','F','F4'),
  (3,15,'I consider personal values.','F','F5'),
  (3,16,'I forgive easily.','F','F6'),
  (3,17,'I encourage people.','F','F7'),
  (3,18,'Others seek my support.','F','F8'),
  (3,19,'Relationships matter to me.','F','F9'),
  (3,20,'I enjoy making people feel included.','F','F10'),
  (4,1,'I plan my day.','J','J1'),
  (4,2,'I finish work before relaxing.','J','J2'),
  (4,3,'I keep things organized.','J','J3'),
  (4,4,'I meet deadlines.','J','J4'),
  (4,5,'I like knowing the plan.','J','J5'),
  (4,6,'I enjoy checklists.','J','J6'),
  (4,7,'I make decisions quickly.','J','J7'),
  (4,8,'I like routines.','J','J8'),
  (4,9,'I prepare in advance.','J','J9'),
  (4,10,'I dislike unfinished work.','J','J10'),
  (4,11,'I enjoy flexibility.','P','P1'),
  (4,12,'I change plans easily.','P','P2'),
  (4,13,'I like exploring options.','P','P3'),
  (4,14,'I work without fixed plans.','P','P4'),
  (4,15,'I enjoy surprises.','P','P5'),
  (4,16,'I keep options open.','P','P6'),
  (4,17,'I decide at the last minute.','P','P7'),
  (4,18,'I adapt quickly.','P','P8'),
  (4,19,'I enjoy spontaneous activities.','P','P9'),
  (4,20,'I like variety in my work.','P','P10')
)
update public.questions q
set text = b.q_text, dimension = b.dim, code = b.q_code
from public.sections s, bank b
where q.section_id = s.id
  and s.order_index between 1 and 4
  and s.order_index = b.section_order
  and q.order_index = b.q_order;